apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rvs-go
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - http:
      paths:
      - path: /ns11 
        backend:
          serviceName: ns-11
          servicePort: 80